<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>defacto</ToolCommandName>
    <Version>0.1.0</Version>
    <Authors>Percyqaz</Authors>
    <Description>Opinionated F# all-in-one formatter and linter</Description>
    <RepositoryUrl>https://github.com/percyqaz/Defacto</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Message.fs" />
    <EmbeddedResource Include="Config\.editorconfig" />
    <EmbeddedResource Include="Config\fsharplint.json" />
    <EmbeddedResource Include="Config\BannedSymbols.txt" />
    <Compile Include="Config\Config.fs" />
    <Compile Include="Rules\PascalCaseSingleArgumentBracketsRule.fs" />
    <Compile Include="Rules\MembersMissingTypeAnnotationRule.fs" />
    <Compile Include="Rules\BannedSymbolsRule.fs" />
    <Compile Include="Rules\AllowShoutingSnakeCaseRule.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fantomas.Core" Version="7.0.5" />
    <PackageReference Include="FSharpLint.Core" Version="0.27.0" />
    <PackageReference Include="Ignore" Version="0.2.1" />
  </ItemGroup>
</Project>